#####################################################################
#                   srsEPC configuration file
#####################################################################

#####################################################################
# MME configuration
#
# mme_code:         8-bit MME code identifies the MME within a group
# mme_group:        16-bit MME group identifier
# tac:              16-bit Tracking Area Code
# mcc:              Mobile Country Code
# mnc:              Mobile Network Code
# apn:              Set Access Point Name (APN)
# mme_bind_addr:    IP bind addr to listen for eNB S1AP connections
# dns_addr:         DNS server address for the UE
# encryption_algo:  Preferred encryption algorithm (EEA0, EEA1, EEA2)
# integrity_algo:   Preferred integrity algorithm (EIA0, EIA1, EIA2)
#
#####################################################################
[mme]
mme_code  = 0x1a
mme_group = 0x0001
tac       = 0x0007
mcc       = 901
mnc       = 70
mme_bind_addr = 127.0.1.100
apn       = srsapn
dns_addr  = 8.8.8.8
encryption_algo = EEA0
integrity_algo  = EIA1
paging_timer    = 2

#####################################################################
# HSS configuration
#
# db_file:  path to CSV database with subscriber info
#####################################################################
[hss]
db_file = /home/timodagoat/code/Broker-lte/configs/user_db.csv

#####################################################################
# SP-GW configuration
#
# gtpu_bind_addr:   GTP-U bind address
# sgi_if_addr:      SGi TUN interface IP address
# sgi_if_name:      SGi TUN interface name
#####################################################################
[spgw]
gtpu_bind_addr = 127.0.1.100
sgi_if_addr    = 172.16.0.1
sgi_if_name    = srs_spgw_sgi

#####################################################################
# PCAP configuration
#####################################################################
[pcap]
enable   = false
filename = /tmp/epc.pcap

#####################################################################
# Log configuration
#
# Log levels: debug, info, warning, error, none
# Hexactvity is limited to 64 bytes by default (hex_limit)
#
# All layers are set to warning level by default.
# An additional "all_level" layer is available to set all layers.
#####################################################################
[log]
all_level  = info
all_hex_limit = 32
filename   = /tmp/epc.log

#####################################################################
# Expert configuration
#####################################################################
[expert]
#ip_netmask = 255.255.255.0


