[rf]
freq_offset = 0
tx_gain = 80
device_name = zmq
device_args = tx_port=tcp://*:3011,rx_port=tcp://localhost:3010,id=ue2,base_srate=11.52e6
[rat.eutra]
dl_earfcn = 2850

[usim]
mode = soft
algo = milenage
opc  = 63bfa50ee6523365ff14c1f45f88737d
k    = 00112233445566778899aabbccddeeff
imsi = 901700123456790
imei = 353490069873320

[nas]
apn = srsapn

[gw]
netns = ue2

[gui]
enable = false

[log]
all_level = warning
all_hex_limit = 32
filename = /tmp/ue2.log


[general]
metrics_csv_enable = true
metrics_period_secs = 1
metrics_csv_filename = /tmp/ue2_metrics.csv
metrics_csv_flush_period_sec = 1
